[phases.setup]
nixPkgs = ["python310", "libGL", "glib", "gcc"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python main.py"
